version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    lnd:
        image: lnd
        build:
          context: lnd/
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    alice:
      extends: lnd
      links:
          - "btcd:blockchain"
      ports:
        - "10009:10009"

    bob:
      extends: lnd
      links:
          - "btcd:blockchain"
      ports:
        - "10101:10009"

    drawbridge:
      build:
        context: ../
        dockerfile: docker/drawbridge/Dockerfile
      links:
        - "alice:lnd"
      volumes:
        - shared:/rpc
      entrypoint: ["docker/drawbridge/start-drawbridge.sh"]


volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during ltcd container recreation.
  litecoin:
    driver: local
